version: '3.7'

services:
  rendezvous:
    image: libp2p/websocket-star-rendezvous:release
    container_name: rendezvous
    restart: always
    ports:
      - "9090:9090"
    networks:
      rendezvous-network:

networks:
  rendezvous-network:
