version: '3.8'

services:
  ganache:
    build: ganache
    container_name: ganache
    expose:
      - 8545
    ports:
      - 8545:8545
    user: root
    volumes:
      - ./ganache/volumes/ganache_db:/home/ganache_db
      - ./ganache/volumes/ganache_keys:/home/ganache_keys
    networks:
      ganache-network:
    restart: always

  rendezvous:
    image: libp2p/js-libp2p-webrtc-star:version-0.20.1
    container_name: rendezvous
    networks:
      rendezvous-network:
    ports:
      - 9090:9090
    restart: always

networks:
  ganache-network:
  rendezvous-network:
