version: '3.7'

services:
  ganache:
    build: ./
    container_name: ganache
    restart: always
    ports:
      - "8545:8545"
    user: root
    volumes:
      - ./volumes/ganache_db:/home/ganache_db
      - ./volumes/ganache_keys:/home/ganache_keys
