export const FETCH_USER_TOPIC = 'FETCH_USER_TOPIC';
export const ADD_USER_TOPIC = 'ADD_USER_TOPIC';
export const UPDATE_USER_TOPICS = 'UPDATE_USER_TOPICS';

export const FETCH_USER_POST = 'FETCH_USER_POST';
export const ADD_USER_POST = 'ADD_USER_POST';
export const UPDATE_USER_POSTS = 'UPDATE_USER_POSTS';

export const UPDATE_ORBIT_DATA = 'UPDATE_ORBIT_DATA';
