const ACCOUNT_CHANGED = 'ACCOUNT_CHANGED';
const AUTH_USER_DATA_UPDATED = 'AUTH_USER_DATA_UPDATED';
const GUEST_USER_DATA_UPDATED = 'GUEST_USER_DATA_UPDATED';
const USER_FETCHING_ERROR = 'USER_FETCHING_ERROR';

export { ACCOUNT_CHANGED, AUTH_USER_DATA_UPDATED, GUEST_USER_DATA_UPDATED, USER_FETCHING_ERROR };
